version: '3.8'
services:
  hub:
    build: ./hub
    ports:
      - '8080:8080'
  
  web-sub-client:
    image: modfin/websub-client:latest
    environment:
      - HOSTNAME=web-sub-client
      - PORT=8080
      - HUB_URL=http://hub:8080
      - TOPIC=a-topic
    depends_on:
      - hub
